version: "3.9"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: http_server_lab1
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/
    working_dir: /app
    command: python -u server.py collection
