services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: http_server_lab2
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/
    working_dir: /app
    command: python -u server_multi.py collection
